[workspace]
resolver = "3"
members = [
    "examples/simple",
    "examples/streaming",
    "examples/ws-streaming",
    "tonic2axum",
    "tonic2axum-build",
]

[patch.crates-io]
prost = { path = "../prost/prost" }
prost-derive = { path = "../prost/prost-derive" }
