[package]
name = "simple"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies.tonic2axum-build]
path = "../.."

[build-dependencies.prost-build]
version = "0.14"
default-features = false

[build-dependencies.tonic-prost-build]
version = "0.14"
default-features = false
